from typing import Protocol


class RecommendationTMDBClient(Protocol):
    def get_trending_movies(self, page: int = 1) -> dict: ...

    def discover_movies(self, **kwargs) -> dict: ...

    def get_person_details(self, person_id: int) -> dict: ...

    def get_movie_recommendations(self, tmdb_id: int, page: int = 1) -> dict: ...
